alien_detection_node:
  ros__parameters:
    model_path: /home/charlottediloreto/projet_yolo26/Orbbec_Femto_Bolt/alien_plushie_v3.pt
    confidence: 0.50
    save_mode: false
    record_mode: true

pose_detection_node:
  ros__parameters:
    model_path: /home/charlottediloreto/projet_yolo26/Orbbec_Femto_Bolt/yolo26n-pose.pt
    confidence: 0.50
    save_mode: false